//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyWebApp.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources_SharedResource_uk {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources_SharedResource_uk() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DummyWebApp.Resources.SharedResources_SharedResource_uk", typeof(SharedResources_SharedResource_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        internal static string NEW_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        internal static string REFRESH_TOKEN_REQUIRED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_REQUIRED", resourceCulture);
            }
        }
        
        internal static string REQUIRED_EMAIL {
            get {
                return ResourceManager.GetString("REQUIRED_EMAIL", resourceCulture);
            }
        }
        
        internal static string REQUIRED_PASSWORD {
            get {
                return ResourceManager.GetString("REQUIRED_PASSWORD", resourceCulture);
            }
        }
        
        internal static string RESET_PASSWORD_TOKEN_REQUIRED {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_TOKEN_REQUIRED", resourceCulture);
            }
        }
        
        internal static string INVALID_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD_LENGTH", resourceCulture);
            }
        }
    }
}
